name: Artifact Uploading

on:
  push:
    branches: [ singleton ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/artifact_upload.yml'
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install DotNet v6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Build
        run: |
          cd Core/

          dotnet build NiTiS/ -c ReleaseWithoutPack -0 ../.build/
          
      - name: Artifact Pack 
        uses: actions/upload-artifact@v2
        with:
          path: .build/*.dll
          
